export const IS_LOGGED_IN_REQUEST = 'App/IS_LOGGED_IN_REQUEST';
export const LOGIN_REQUEST = 'App/LOGIN_REQUEST';
export const LOGOUT_REQUEST = 'App/LOGOUT_REQUEST';
export const LOGIN_SUCCESS = 'App/LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'App/LOGOUT_SUCCESS';
export const REGISTER_REQUEST = 'App/REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'App/REGISTER_SUCCESS';
